version: "3.4"

services:
  postgres:
    image: postgres:9.6.10-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: YyjRCj0VfCgP
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./data/postgres/data:/var/lib/postgresql/data"
    ports:
      - "7432:5432/tcp"
    healthcheck:
      test: echo "SELECT 1" | psql --username postgres --quiet --no-align --tuples-only | grep -q 1 || exit 1
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s
